### ISSUE TITLE
User Setting for Avatar provider

### ISSUE THREAD

**Issue by Vorror** [Exelord/git-commits#1]
Currently, the Github avatar url is hardcoded as the image for commits. It would great if there was a user setting that allowed us to select which image provider to use. Example:

```js
{
  "git-commits.avatarProvider": "gitlab" // "github | gravatar"
}
```

Api reference:

[Gitlab Api](https://docs.gitlab.com/ee/api/avatar.html)
[Gravatar](https://en.gravatar.com/site/implement/images)

**Comment by Exelord** [comment]
Oh yeah! I think we should go even further! Determine it by origin url. If the repo is on githu use GH avatars if GL gitlab and if other then gravatars. What do you think?

**Comment by Vorror** [comment]
Definitely! I would still keep the setting for users that self-host (Gitlab and Github Enterprise).

**Comment by Exelord** [comment]
Ok, Gravatars are already supported as fallback :) 
However, I see GL don't have content API :/

**Comment by Vorror** [comment]
Is ```GET https://gitlab.com/api/v4/avatar?email=${email}&size=32``` not what you're looking for?

**Comment by Exelord** [comment]
This returns a JSON, but I expect a file :/

**Comment by Vorror** [comment]
@Exelord Correct, is that an issue? The json contains the path of the avatar url. I guess that requires the code to be marginally different for gitlab.

**Comment by Exelord** [comment]
It is as we need to have a static link. We cannot modify it on the go after we resolve it :/

**Comment by Exelord** [comment]
This feature wont be possible for now as vscode does not support async links for icons :/
