### ISSUE TITLE
Does not work when used with git from WSL

### ISSUE THREAD

**Issue by l0ner** [Exelord/git-commits#12]
**OS**: Windows 10 2004 build 19041.450
**VSCode**: 1.47.2
**Git for windows**: not installed

Steps to reproduce:

1. Uninstall git for windows
2. Install git in Linux in WSL
3. Use [https://github.com/HanabishiRecca/WslShortcut](https://github.com/HanabishiRecca/WslShortcut) to point VSCode to use git in WSL
3.1. Download WslShortcut.exe from [Releases](https://github.com/HanabishiRecca/WslShortcut/releases)
3.2. Rename it to git.exe and place somewhere (in my case `"D:\WSL\shortcuts\git.exe"`)
3.3. Set VSCode setting `"git.path"` to `"D:\\WSL\\shortcuts\\git.exe"`

If all this is done the git in VSCode works correctly (i can stage changes for commits, commit, push, pull, and so on). [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens), [Git Graph](https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph) and [Git Tags](https://marketplace.visualstudio.com/items?itemName=howardzuo.vscode-git-tags) also work correctly. The only issue is with this extension.

All errors are of kind "git log (...) is not a recognized command."

**Workaround**: Add location of the git.exe shortcut app to windows `PATH`.

Given that it works with git in the `PATH`, I'd guess this extension does not use the `git.path` (like the other listed git extensions) setting and instead relies on git being present in the `PATH`. Is this true?

**Comment by Exelord** [comment]
Thanks for reporting. Indeed thats the solution. to use git.path instead of direct git command access :) Will fix it soon!

**Comment by Exelord** [comment]
Can you try with `v3.7.10`?  :)

**Comment by l0ner** [comment]
Just checked, now it works as it should. Thanks for the quick fix!

**Comment by Exelord** [comment]
Enjoy :)
