### ISSUE TITLE
3.7.10 Breaking change. Non-escaped character; failing to detect spaces in config strings?

### ISSUE THREAD

**Issue by carsonpowers** [Exelord/git-commits#13]
![image](https://user-images.githubusercontent.com/11263423/91212237-8f034480-e6d5-11ea-82d3-7bf314216be0.png)

I can revert to v3.7.9 and the error goes away.

Running on Windows 10

**Comment by mloldacre** [comment]
I'm having the same issue @carsonpowers! Thanks for showing this.

**Comment by Exelord** [comment]
Oh! I don't have access to windows so playing blindly with it. Do you know how the command should look like there to run it correctly? :)

**Comment by Exelord** [comment]
Should be fixed in the latest version :) v3.7.11

**Comment by mloldacre** [comment]
It works! Thanks for fixing it! Really appreciate your extension!
