### ISSUE TITLE
Show changes in a tree view

### ISSUE THREAD

**Issue by harkairt** [Exelord/git-commits#16]
Hey! This is the extension I am looking for!! (how is this not a vscode functionality, to list commits and show their diffs?)

One thing which would make it perfect for me, is to have a way of showing the files in a **tree like** manner.

Although I've modest experience in vscode extensions, but since the project structure looks mature (nicely organized, typed) I think I'll fiddle with this feature when I'll have more time at my disposal.

**Comment by Exelord** [comment]
> (how is this not a vscode functionality, to list commits and show their diffs?)

I know right? Its so obvious. 

> One thing which would make it perfect for me, is to have a way of showing the files in a tree like manner.

Yes, we can add a switch for that. Though, the default still will be the list. :)

**Comment by Exelord** [comment]
Done in v3.10.0 🎉
