### ISSUE TITLE
[Feature Suggestion] Open committed file with diff editor

### ISSUE THREAD

**Issue by robertoentringer** [Exelord/git-commits#2]
Open committed file with diff editor to compare with the current file like :

![Capture d’écran 2020-02-23 à 13 41 00](https://user-images.githubusercontent.com/1759811/75112278-8789b280-5642-11ea-968a-b17d4fbd74df.png)

**Comment by Exelord** [comment]
This is the next step :) Im struggling with vscode api to achieve that. If you know how to do it, any help is welcome :)

**Comment by robertoentringer** [comment]
Great! I'm going to take a look at this and see if I can help...

**Comment by robertoentringer** [comment]
@Exelord, take a look in the @masliu's repo : [vscode-simple-git-history](https://github.com/masliu/vscode-simple-git-history). He did exactly that!

**P.S:** at this time, my limited knowledge of TS and the development of vscode extentions did not allow me to go any further ...

**Comment by Exelord** [comment]
Wow... thanks a lot! I will take a look :)

**Comment by Exelord** [comment]
Now you can diff :) v1.1.0 🎉

**Comment by robertoentringer** [comment]
Thanks !
