### ISSUE TITLE
File names don't display properly in tree on Windows

### ISSUE THREAD

**Issue by stkb** [Exelord/git-commits#23]
Hi, thanks so much for this extension. It really saves me time to have the list of commits right there in the side bar rather than continually jumping in & out of `gitk`.

I did however have a problem that the file paths shown for each commit were all absolute, which makes it impossible to see what's what at a glance in the narrow pane.

![image](https://user-images.githubusercontent.com/6125444/156588935-e6676e26-dc4e-4f8b-b405-f017d3a0fa3f.png)

I found that it was because the code in `changes.ts` uses the `.fsPath` property of URIs, which on windows uses backslashes in paths, but all the code there assumes forward slashes, so it isn't working as intended.

You can use the `.path` property instead (which is always forwardslashes), or accomodate for backslashes in some other way. I can help if you like.

**Comment by Exelord** [comment]
Thank you for reporting. I don't use windows so was not able to catch it. Should be fixed in 3.11.1 :) Let me know if it works!

**Comment by stkb** [comment]
Thanks it works great now!

It's no biggie at all but I did just notice another occurence here where the function uses `.fsPath` & "/":

https://github.com/Exelord/git-commits/blob/597313abf51457fc6a8151fab7b28379544ff598/src/git-manager.ts#L120-L134

So on Windows it's just sorting on full path atm (which is fine?). I'm not actually sure what the difference is. No rush with that one though.
