### ISSUE TITLE
Incorrect time displayed when month changes

### ISSUE THREAD

**Issue by leosdad** [Exelord/git-commits#25]
Today is 05/03/2022. Git Commits shows "1 month ago" for commits made just 6 days ago (Apr 27 2022). This is misleading. IMHO it should read "6 days ago".

Thanks in advance for looking into this.

**Comment by Exelord** [comment]
Hi, thanks for reporting :) I will take a look at it soon! Till this time you can also use a tootltip (on hover) to display the full commit date
