### ISSUE TITLE
stash apply throws an error

### ISSUE THREAD

**Issue by devmor-j** [Exelord/git-commits#30]
System:
- vscode: 1.71
- git: 2.37.3

Error message:
`
Error running command gitCommits.stashApply: Cannot read properties of undefined (reading 'applyStash'). This is likely caused by the extension that contributes gitCommits.stashApply.
`

This is shown as a popup notification in vscode.

If I exec `git stash apply` it works but using extension (has a button to do so) that error is occurred.

BTW Thanks for making this extension it really is helpful and awesome.

**Comment by Exelord** [comment]
Thanks :) Looks like vscode changed its api. I will fix it soon

**Comment by devmor-j** [comment]
Great I've tested it and everything is working fine 👍

**Comment by Exelord** [comment]
Fixed in 4.2.1 :)
