### ISSUE TITLE
Since 4.1.2 commits are not more displayed

### ISSUE THREAD

**Issue by Sepp-PS** [Exelord/git-commits#34]
With the last update to 4.1.2 no commits are more displayed. 
With a rollback to 4.1.1 they are visible again.

**Comment by Exelord** [comment]
That's interesting. It works well for me. Could you please give me more info on your system, git version, vscode etc?

**Comment by Sepp-PS** [comment]
I have the same situation on min two systems.
a) Windows 11 22H2, vsCode 1.74, Git 2.38.1
b) Windows 10 21H2, vsCode 1.74 Git 2.37.1
both are German systems. 
In the view that is not a generic error I will made a Test on Linux Mint as well.

**Comment by Exelord** [comment]
Ahh.. it's probably Windows shell. It's hard for me to test that as I dont have any machine and not able to virtualize.

It's related to the way Im calling git

```
return asyncExec(`${this.gitApi.git.path} ${args.join(' ')}`, { cwd: this.repository.rootUri.fsPath,  })
```

Probably this command is not executed properly. Might me related again to `/` vs`\`.

**Comment by Sepp-PS** [comment]
Linux Mint 21.0, vsCode 1.74, git 2.34.1
And it works. So yes, it looks like a Windows backslash bug.

**Comment by Exelord** [comment]
Could you try 4.1.3?

**Comment by Sepp-PS** [comment]
How can I do it? vsCode don't find it yet, I don't found anything for download.

**Comment by Sepp-PS** [comment]
Now it is there.

**Comment by Exelord** [comment]
It can take 5min to show up :) Publishing is not instant

**Comment by Sepp-PS** [comment]
Tested on both Windows systems and on the Linux system and all work again.
Perfect. Problem solved. 
Thanks a lot.

**Comment by Exelord** [comment]
Happy using 🙌

**Comment by Exelord** [comment]
I just want to put it there 🤯 This ChatGPT basically solved this issue.


<img width="799" alt="PNG image" src="https://user-images.githubusercontent.com/1469375/206723959-d1c73cea-de16-4f89-ad06-1f66785443d4.png">
<img width="723" alt="PNG image" src="https://user-images.githubusercontent.com/1469375/206723964-18350ec4-1336-4e30-a902-44b20b18f590.png">
