### ISSUE TITLE
[Bug] Git command failed for workspaces with spaces in path

### ISSUE THREAD

**Issue by zep-roman-savchuk** [Exelord/git-commits#4]
Hello, Exelord

While using extension I come to problem with spaces in workspace folder

Here error description: 
```
Command failed: git -C c:\D_Drive\QVDev\DEV\QVApps\HR KPI log -20 --pretty=format:'{ #@Xhash#@X: #@X%H#@X, #@XshortHash#@X: #@X%h#@X, #@Xauthor#@X: #@X%an#@X, #@Xemail#@X: #@X%ae#@X, #@XtimePassed#@X: #@X%cr#@X, #@Xsubject#@X: #@X%s#@X, #@Xdate#@X: #@X%cI#@X, #@XparentHash#@X: #@X%P#@X, #@XparentShortHash#@X: #@X%p#@X }'
fatal: cannot change to 'c:\D_Drive\QVDev\DEV\QVApps\HR': No such file or directory
```
Here `c:\D_Drive\QVDev\DEV\QVApps\HR KPI` is my workspace folder, but it pasted in git command without single quotes, so git think, that `c:\D_Drive\QVDev\DEV\QVApps\HR` is folder.

I investigate your sources and found that `src\git-manager.ts:39`
``` ts
return this.executeCommand(`git -C ${this.workspaceFolder} ${command}`);
```

I suggest to wrap workspace folder path in single quotes like this:
``` ts
return this.executeCommand(`git -C '${this.workspaceFolder}' ${command}`);
```
This should fix problem =)

**Comment by Exelord** [comment]
Thanks a lot :) Done and released.
