### ISSUE TITLE
Updated UI not visible

### ISSUE THREAD

**Issue by rohku** [Exelord/git-commits#40]
Greetings,

I do not see the new UI that matches the old Atom-style categories when opening up Source Control.  Is there a setting I missed?

My version of VSCode:

Version: 1.79.2 (Universal)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:58:52.392Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

**Comment by Exelord** [comment]
Hey! Could you show be a screenshot and describe the issue a little more? Not sure I understand.

**Comment by rohku** [comment]
Apologies for the late reply.  There is nothing wrong with the UI.

I mistakenly was expecting the Atom UI feature where unstaged and staged changes were in separate windows.

Example:
![image](https://github.com/Exelord/git-commits/assets/8826849/3d303ddc-56a6-49b5-9e80-5f8c2390d15a)

**Comment by Exelord** [comment]
I see :) This functionality is already built-in in vscode.
