### ISSUE TITLE
[BUG] 1.4.4

### ISSUE THREAD

**Issue by R4PH4** [Exelord/git-commits#5]
I have this bug when launching vscode part git

![Capture](https://user-images.githubusercontent.com/58464986/75788648-d634fc00-5d68-11ea-9731-10a6c9c8ac5a.JPG)

**Comment by Exelord** [comment]
Thanks a lot for reporting! Can you give me more details on that? Your system info, do you have git repo initialized, how to reproduce it?

**Comment by R4PH4** [comment]
![image](https://user-images.githubusercontent.com/58464986/75858900-5acf5b00-5df9-11ea-97d7-d1a53679904e.png)

**Comment by R4PH4** [comment]
![image](https://user-images.githubusercontent.com/58464986/75858974-7b97b080-5df9-11ea-80b1-f6d790903f95.png)

**Comment by Exelord** [comment]
do you have git repo initialized, how to reproduce it?

**Comment by R4PH4** [comment]
![image](https://user-images.githubusercontent.com/58464986/75884591-69336c00-5e25-11ea-9fff-405c2c7867f2.png)

**Comment by puz-archie** [comment]
git-manager.js

#38 ' to " replace

>             const result = yield this.executeGitCommand(`log -${limit} --pretty=format:'{ #@Xhash#@X: #@X%H#@X, #@XshortHash#@X: #@X%h#@X, #@Xauthor#@X: #@X%an#@X, #@Xemail#@X: #@X%ae#@X, #@XtimePassed#@X: #@X%cr#@X, #@Xsubject#@X: #@X%s#@X, #@Xdate#@X: #@X%cI#@X, #@XparentHash#@X: #@X%P#@X, #@XparentShortHash#@X: #@X%p#@X }'`).catch((error) => {

to

>             const result = yield this.executeGitCommand(`log -${limit} --pretty=format:"{ #@Xhash#@X: #@X%H#@X, #@XshortHash#@X: #@X%h#@X, #@Xauthor#@X: #@X%an#@X, #@Xemail#@X: #@X%ae#@X, #@XtimePassed#@X: #@X%cr#@X, #@Xsubject#@X: #@X%s#@X, #@Xdate#@X: #@X%cI#@X, #@XparentHash#@X: #@X%P#@X, #@XparentShortHash#@X: #@X%p#@X }"`).catch((error) => {

**Comment by Exelord** [comment]
Im moving away from git integration to vscode git api. The update will land soon :)

**Comment by R4PH4** [comment]
perfect !!! thank you :)

**Comment by Exelord** [comment]
Fixed! Try it out :)
