### ISSUE TITLE
Fails as of May 2020 with an error message

### ISSUE THREAD

**Issue by leosdad** [Exelord/git-commits#7]
Recently (may 2020) it began to fail with the following error:

```
Command failed: git log -n20 --first-parent --pretty=format:'{%n  "hash": "%H",%n  "parents": "%P",%n  "message": "%s",%n  "authorName": "%aN",%n  "authorDate": "%aD",%n  "authorEmail": "%aE"%n},' --
fatal: bad revision 'hash:'
```

The latest commits do not appear anymore. I've positively related this error with this extension so I've disabled it.

Is there a fix? Thanks in advance.

**Comment by Exelord** [comment]
Thanks for reporting! Im using it all the time and didn't noticed any issue. Could you give me your spec info? OS, vs-code version, git-version, extension version?

**Comment by Exelord** [comment]
Try new version v3.3.1 and let me know :)

**Comment by leosdad** [comment]
Thanks for the fast response! Version 3.3.1 doesn't show any errors, but commits don't appear in the Commits pane, so unfortunately it is not working for me. The button Undo last commit works, though. My system is Windows 10 Pro v. 1903, VS Code v. 1.45.1, git version 2.22.0.windows.1.

**Comment by Exelord** [comment]
Try 3.4.1 and let me know :)

**Comment by leosdad** [comment]
Good news! 3.4.1 is working again. Many thanks for the fix!

**Comment by leosdad** [comment]
A suggestion... Perhaps you should update the changelog to reflect those fixes.

**Comment by Exelord** [comment]
Thanks a lot for reporting the bug :) I maintain the ext just for myself, but Im always willing to fix any noticeable bug that others have. I really would love see that ext as a native ext built in. :)
